## Importing packages

In [20]:
import numpy as np                        # Implemennts milti-dimensional array and matrices
import pandas as pd                       # For data manipulation and analysis

import pandas_profiling

import matplotlib.pyplot as plt           # Plotting library for Python programming language and it's numerical mathematics extension NumPy
import seaborn as sns                     # Provides a high level interface for drawing attractive and informative statistical graphics
%matplotlib inline
sns.set()

from subprocess import check_output

ModuleNotFoundError: ignored

## Importing the Dataset

In [21]:
FB_data_df = pd.read_csv('https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Projects/facebook_data.csv')           # Importing dataset using pd.read_csv

## Data Profiling

###  1 Understanding the Dataset

In [22]:
FB_data_df.drop_duplicates()

,userid,age,dob_day,dob_year,dob_month,gender,tenure,friend_count,friendships_initiated,likes,likes_received,mobile_likes,mobile_likes_received,www_likes,www_likes_received
0,2094382,14,19,1999,11,male,266.0,0,0,0,0,0,0,0,0
1,1192601,14,2,1999,11,female,6.0,0,0,0,0,0,0,0,0
2,2083884,14,16,1999,11,male,13.0,0,0,0,0,0,0,0,0
3,1203168,14,25,1999,12,female,93.0,0,0,0,0,0,0,0,0
4,1733186,14,4,1999,12,male,82.0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98998,1268299,68,4,1945,4,female,541.0,2118,341,3996,18089,3505,11887,491,6202
98999,1256153,18,12,1995,3,female,21.0,1968,1720,4401,13412,4399,10592,2,2820
99000,1195943,15,10,1998,5,female,111.0,2002,1524,11959,12554,11959,11462,0,1092
99001,1468023,23,11,1990,4,female,416.0,2560,185,4506,6516,4506,5760,0,756
99002,1397896,39,15,1974,5,female,397.0,2049,768,9410,12443,9410,9530,0,2913

In [23]:
FB_data_df.shape

(99003, 15)

In [24]:
FB_data_df.columns

Index(['userid', 'age', 'dob_day', 'dob_year', 'dob_month', 'gender', 'tenure',
       'friend_count', 'friendships_initiated', 'likes', 'likes_received',
       'mobile_likes', 'mobile_likes_received', 'www_likes',
       'www_likes_received'],
      dtype='object')

In [25]:
FB_data_df.head()

,userid,age,dob_day,dob_year,dob_month,gender,tenure,friend_count,friendships_initiated,likes,likes_received,mobile_likes,mobile_likes_received,www_likes,www_likes_received
0,2094382,14,19,1999,11,male,266.0,0,0,0,0,0,0,0,0
1,1192601,14,2,1999,11,female,6.0,0,0,0,0,0,0,0,0
2,2083884,14,16,1999,11,male,13.0,0,0,0,0,0,0,0,0
3,1203168,14,25,1999,12,female,93.0,0,0,0,0,0,0,0,0
4,1733186,14,4,1999,12,male,82.0,0,0,0,0,0,0,0,0

In [26]:
FB_data_df.tail()

,userid,age,dob_day,dob_year,dob_month,gender,tenure,friend_count,friendships_initiated,likes,likes_received,mobile_likes,mobile_likes_received,www_likes,www_likes_received
98998,1268299,68,4,1945,4,female,541.0,2118,341,3996,18089,3505,11887,491,6202
98999,1256153,18,12,1995,3,female,21.0,1968,1720,4401,13412,4399,10592,2,2820
99000,1195943,15,10,1998,5,female,111.0,2002,1524,11959,12554,11959,11462,0,1092
99001,1468023,23,11,1990,4,female,416.0,2560,185,4506,6516,4506,5760,0,756
99002,1397896,39,15,1974,5,female,397.0,2049,768,9410,12443,9410,9530,0,2913

In [27]:
FB_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99003 entries, 0 to 99002
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   userid                 99003 non-null  int64
 1   age                    99003 non-null  int64
 2   dob_day                99003 non-null  int64
 3   dob_year               99003 non-null  int64
 4   dob_month              99003 non-null  int64
 5   gender                 98828 non-null  object
 6   tenure                 99001 non-null  float64
 7   friend_count           99003 non-null  int64
 8   friendships_initiated  99003 non-null  int64
 9   likes                  99003 non-null  int64
 10  likes_received         99003 non-null  int64
 11  mobile_likes           99003 non-null  int64
 12  mobile_likes_received  99003 non-null  int64
 13  www_likes              99003 non-null  int64
 14  www_likes_received     99003 non-null  int64
dtypes: float64(1), int64(13), object(1)
memory usage: 11.3+ MB

In [28]:
FB_data_df.describe()

,userid,age,dob_day,dob_year,dob_month,tenure,friend_count,friendships_initiated,likes,likes_received,mobile_likes,mobile_likes_received,www_likes,www_likes_received
count,9.900300e+04,99003.000000,99003.000000,99003.000000,99003.000000,99001.000000,99003.000000,99003.000000,99003.000000,99003.000000,99003.000000,99003.000000,99003.000000,99003.000000
mean,1.597045e+06,37.280224,14.530408,1975.719776,6.283365,537.887375,196.350787,107.452471,156.078785,142.689363,106.116300,84.120491,49.962425,58.568831
std,3.440592e+05,22.589748,9.015606,22.589748,3.529672,457.649874,387.304229,188.786951,572.280681,1387.919613,445.252985,839.889444,285.560152,601.416348
min,1.000008e+06,13.000000,1.000000,1900.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.298806e+06,20.000000,7.000000,1963.000000,3.000000,226.000000,31.000000,17.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.596148e+06,28.000000,14.000000,1985.000000,6.000000,412.000000,82.000000,46.000000,11.000000,8.000000,4.000000,4.000000,0.000000,2.000000
75%,1.895744e+06,50.000000,22.000000,1993.000000,9.000000,675.000000,206.000000,117.000000,81.000000,59.000000,46.000000,33.000000,7.000000,20.000000
max,2.193542e+06,113.000000,31.000000,2000.000000,12.000000,3139.000000,4923.000000,4144.000000,25111.000000,261197.000000,25111.000000,138561.000000,14865.000000,129953.000000

In [29]:
FB_data_df.isnull().sum()

userid                     0
age                        0
dob_day                    0
dob_year                   0
dob_month                  0
gender                   175
tenure                     2
friend_count               0
friendships_initiated      0
likes                      0
likes_received             0
mobile_likes               0
mobile_likes_received      0
www_likes                  0
www_likes_received         0
dtype: int64

From the above output we can see that __gender__ and __tensure__ columns contains __null values__. We will see how to deal with them.

###  2 Pre Profiling

In [30]:
'''
profile = pandas_profiling.ProfileReport(FB_data_df)
profile.to_file(outputfile = "facebook_before_preprocessing.html")

'''

'\nprofile = pandas_profiling.ProfileReport(FB_data_df)\nprofile.to_file(outputfile = "facebook_before_preprocessing.html")\n\n'

In [31]:
FB_data_df.gender = FB_data_df.gender.fillna(FB_data_df['gender'].mode()[0])
# filling the null values in gender column as na

In [32]:
FB_data_df['dob'] =  FB_data_df['dob_month'].map(str) + '/' + FB_data_df['dob_day'].map(str) + '/' + FB_data_df['dob_year'].map(str)
# Creating a new column dob from dob_day dob_year dob_month

In [33]:
FB_data_df['dob'] = pd.to_datetime(FB_data_df['dob'], format='%m/%d/%Y')
# Converting the dob column into pandas datetime format

In [34]:
FB_data_df.head()

,userid,age,dob_day,dob_year,dob_month,gender,tenure,friend_count,friendships_initiated,likes,likes_received,mobile_likes,mobile_likes_received,www_likes,www_likes_received,dob
0,2094382,14,19,1999,11,male,266.0,0,0,0,0,0,0,0,0,1999-11-19
1,1192601,14,2,1999,11,female,6.0,0,0,0,0,0,0,0,0,1999-11-02
2,2083884,14,16,1999,11,male,13.0,0,0,0,0,0,0,0,0,1999-11-16
3,1203168,14,25,1999,12,female,93.0,0,0,0,0,0,0,0,0,1999-12-25
4,1733186,14,4,1999,12,male,82.0,0,0,0,0,0,0,0,0,1999-12-04

In [35]:
FB_data_df.tail()

,userid,age,dob_day,dob_year,dob_month,gender,tenure,friend_count,friendships_initiated,likes,likes_received,mobile_likes,mobile_likes_received,www_likes,www_likes_received,dob
98998,1268299,68,4,1945,4,female,541.0,2118,341,3996,18089,3505,11887,491,6202,1945-04-04
98999,1256153,18,12,1995,3,female,21.0,1968,1720,4401,13412,4399,10592,2,2820,1995-03-12
99000,1195943,15,10,1998,5,female,111.0,2002,1524,11959,12554,11959,11462,0,1092,1998-05-10
99001,1468023,23,11,1990,4,female,416.0,2560,185,4506,6516,4506,5760,0,756,1990-04-11
99002,1397896,39,15,1974,5,female,397.0,2049,768,9410,12443,9410,9530,0,2913,1974-05-15

In [36]:
FB_data_df.isnull().sum()

userid                   0
age                      0
dob_day                  0
dob_year                 0
dob_month                0
gender                   0
tenure                   2
friend_count             0
friendships_initiated    0
likes                    0
likes_received           0
mobile_likes             0
mobile_likes_received    0
www_likes                0
www_likes_received       0
dob                      0
dtype: int64

###  3 Post Profiling

In [37]:
'''
profile = pandas_profiling.ProfileReport(FB_data_df)
profile.to_file(outputfile="facebook_after_preprocessing.html")

'''

'\nprofile = pandas_profiling.ProfileReport(FB_data_df)\nprofile.to_file(outputfile="facebook_after_preprocessing.html")\n\n'

## Questions

###  1 Who is more likely to use facebook, male or female?

In [38]:
sns.countplot(x='gender', data=FB_data_df).set_title('Count plot for user.')

NameError: ignored

__Male__ use facebook more as compared to __Female__

In [ ]:
FB_data_df.groupby(['gender'])['gender'].count()

There are __40254 Female__ users and __58749 Male__ users

###  2 Which age group uses facebook more?

In [ ]:
as_fig = sns.FacetGrid(FB_data_df,aspect=5)

as_fig.map(sns.kdeplot,'age',shade=True)

oldest = FB_data_df['age'].max()

as_fig.set(xlim=(0,oldest))

as_fig.add_legend()
plt.title('Age distribution using FacetGrid')

In [ ]:
sns.set(color_codes=True)                                                # Plot a histogram of the respondents' ages (remove any NaN values)
sns.set_palette(sns.color_palette("muted"))
sns.set(rc={'figure.figsize':(12,9)})
sns.distplot(FB_data_df["age"].dropna());

- In the given facebook data __People__ of Age __15-25__ yrs are in majority.
- There is a small peak between 45-70 years

###  3 Which year group uses facebook more?

In [ ]:
bins = [1900, 1920, 1940, 1960, 1980, 2000]
FB_data_df.groupby(pd.cut(FB_data_df['dob_year'], bins=bins)).dob_year.count().plot(kind='bar', figsize=(5,5))
plt.show()

- From the given data it is seen that there is a __rise in__ the __use__ of facebook __after__ the __year 1940__.
- People from the year group __1980 - 2000 use__ facebook the __most__.

###  4 Which gender had more friend count more ?

In [ ]:
gen_vs_friend_count = FB_data_df[['gender','friend_count']].drop_duplicates().sort_values(by='gender').groupby(['gender'])['friend_count'].agg('count')
gen_vs_friend_count.plot(kind='bar', legend = (0.60,0.9), x = ("gender", 10), y = ("friend_count", 10), title = ("Total gender w.r.t friend_count"), figsize=(5,5))

- __Women__ have __more friends__ than men on facebook

###  5 Which gender initiated friendship more ?

In [ ]:
gen_vs_friendships_initiated = FB_data_df[['gender','friendships_initiated']].drop_duplicates().sort_values(by='gender').groupby(['gender'])['friendships_initiated'].agg('count')
gen_vs_friendships_initiated.plot(kind='pie', legend = (0.60,0.9), x = ("gender", 10), y = ("friendships_initiated", 10), title = ("Total gender w.r.t friendships_initiated"), figsize=(6,6))

- __Friendships initiated__ are __more__ in case of __men__ than women

###  6 Which gender has more likes ?

In [ ]:
gen_vs_likes = FB_data_df[['gender','likes']].sort_values(by='gender').drop_duplicates().groupby(['gender'])['likes'].agg('count')
gen_vs_likes.plot(kind='bar', legend = (0.60,0.9), x = ("gender", 10), y = ("likes", 10), title = ("Total gender w.r.t likes"), figsize=(5,5))

- __Female__ population has __more likes__ as compared to male population.

###  Likes comparision ?

In [ ]:
gen_vs_likes_recv = FB_data_df[['gender','likes_received']].sort_values(by='gender').drop_duplicates().groupby(['gender'])['likes_received'].agg('count')
gen_vs_likes_recv.plot(kind='bar', legend = (0.70,0.10), x = ("gender", 15), y = ("likes_received", 15), title = ("Total gender w.r.t likes_received"), figsize=(5, 5))

- __Female__ population received __more likes__ as compared to male population.

In [ ]:
gen_vs_mobile_likes = FB_data_df[['gender','mobile_likes']].sort_values(by='gender').drop_duplicates().groupby(['gender'])['mobile_likes'].agg('count')
gen_vs_mobile_likes.plot(kind='bar', legend = (0.70,0.10), x = ("gender", 15), y = ("mobile_likes", 15), title = ("Total gender w.r.t mobile_likes"), figsize=(5, 5),colormap='hot')

gen_vs_moblikes_recv = FB_data_df[['gender','mobile_likes_received']].sort_values(by='gender').drop_duplicates().groupby(['gender'])['mobile_likes_received'].agg('count')
gen_vs_moblikes_recv.plot(kind='bar', legend = (0.70,0.10), x = ("gender", 15), y = ("mobile_likes_received", 15), title = ("Total gender w.r.t mobile_likes_received"), figsize=(5, 5),colormap='gist_rainbow')

gen_vs_www_likes = FB_data_df[['gender','www_likes']].sort_values(by='gender').drop_duplicates().groupby(['gender'])['www_likes'].agg('count')
gen_vs_www_likes.plot(kind='bar', legend = (0.70,0.10), x = ("gender", 15), y = ("www_likes", 15), title = ("Total gender w.r.t www_likes"), figsize=(5, 5),colormap='summer')

gen_vs_wwwlikes_rec = FB_data_df[['gender','www_likes_received']].sort_values(by='gender').drop_duplicates().groupby(['gender'])['www_likes_received'].agg('count')
gen_vs_wwwlikes_rec.plot(kind='bar', legend = (0.70,0.10), x = ("gender", 15), y = ("www_likes_received", 15), title = ("Total gender w.r.t www_likes_received"), figsize=(5, 5))

- __More likes from mobile__ as compared to site though few users still use sites
- __Female__ population __gave more likes__ as compared to male population.